language: node_js

install:
  - npm ci

script:
  - npm test
  - npm audit

notifications:
  email: false
  slack:
    secure: t4WnMMYlN6EebbxU/vQCSNDow+30yEGZ2AOgxexlF1c7Q2tg/FdVbSUw3e6gvoOSPVVCLhO25LvniCU5mcqE8M3EWZro4+IU+GXvPCaye2efJ5CZUJ0gujeC57OEnO2JTM7OuZB5b3BtDtYNEsQgYmORARw4fT+sKPjJ5l6XvUi+blyomU8cBHC1WnI4+NmCZQQmpvr7LotqxDnMjiXS28fToulZnMp5kgHEBHMBSU28gqyxhmHYDmR2nIooVFlePgPOAWoFEAnAgwrP8vtkhc0MhTELvRlNgCZEZDiGHqAJFLcaCgKy3Bh+BTNVzpAoYtRPx9u/pgN+0eNXQobvX6rDQzIyOyLDvw0b6Xd5K/tv8RmgSreblSUMIxa6VBAvpLLt2F+Mx1/YQ9Y2yK1lX7MDHm3+3LlGFv3mjydBFk9EgCxNqqdimHAUTJB2MeoHQKGuI9qE0nZlvIULv7k9u/TMxig73cyUfaebdvJG1jpMDLA2QGpzH1tgzsAIC9MISOAbmjUJnnbjCm5Vbzk6iTKzCMmiZSPdn7OR5eyUs78tBK5aTvTPqaY5nuKS1VKmxBmLqiXVEtIXHcXylwLoOsNc0ibuPkevsl2giXb10ATtyYyrdF785908vJMkct5lNMOGcvkmf9DhGtjYAVj8B5eIC7N6sMr5AtuI5xD7EcA=
